delta = 0.001
radius_factor = 2.0


[[bodies]]
pos = [0, 1, 0]
speed = [1, 0, 0]
mass = 4
color = [1, 0, 0, 1]
trail_color = [0.5, 0.5, 0.5, 1]

[[bodies]]
pos = [0, -1, 0]
speed = [-1, 0, 0]
mass = 4
color = [0, 0, 1, 1]
trail_color = [0.5, 0.5, 0.5, 1]

